apiVersion: v1
kind: Service
metadata:
  name: store-engine-orchestrator-service
spec:
  selector:
    app: store-engine-orchestrator-ms
  ports:
    - protocol: TCP
      name: orchestrator-tcp-port
      port: 2500
      targetPort: 2500
  type: NodePort
